// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1, 0}
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=search.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

// Key is partition or partition/partitionUUID.  Value is seq.
// For example, a DCP data source might have the key as either
// "vbucketId" or "vbucketId/vbucketUUID".
type ConsistencyVectors struct {
	ConsistencyVector    map[string]uint64 `protobuf:"bytes,1,rep,name=ConsistencyVector,proto3" json:"ConsistencyVector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConsistencyVectors) Reset()         { *m = ConsistencyVectors{} }
func (m *ConsistencyVectors) String() string { return proto.CompactTextString(m) }
func (*ConsistencyVectors) ProtoMessage()    {}
func (*ConsistencyVectors) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *ConsistencyVectors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsistencyVectors.Unmarshal(m, b)
}
func (m *ConsistencyVectors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsistencyVectors.Marshal(b, m, deterministic)
}
func (m *ConsistencyVectors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsistencyVectors.Merge(m, src)
}
func (m *ConsistencyVectors) XXX_Size() int {
	return xxx_messageInfo_ConsistencyVectors.Size(m)
}
func (m *ConsistencyVectors) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsistencyVectors.DiscardUnknown(m)
}

var xxx_messageInfo_ConsistencyVectors proto.InternalMessageInfo

func (m *ConsistencyVectors) GetConsistencyVector() map[string]uint64 {
	if m != nil {
		return m.ConsistencyVector
	}
	return nil
}

// ConsistencyParams represent the consistency requirements of a
// client's request.
type ConsistencyParams struct {
	// A Level value of "" means stale is ok; "at_plus" means we need
	// consistency at least at or beyond the consistency vector but
	// not before.
	Level string `protobuf:"bytes,1,opt,name=Level,proto3" json:"Level,omitempty"`
	// Keyed by indexName.
	Vectors              map[string]*ConsistencyVectors `protobuf:"bytes,2,rep,name=Vectors,proto3" json:"Vectors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Results              string                         `protobuf:"bytes,3,opt,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ConsistencyParams) Reset()         { *m = ConsistencyParams{} }
func (m *ConsistencyParams) String() string { return proto.CompactTextString(m) }
func (*ConsistencyParams) ProtoMessage()    {}
func (*ConsistencyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *ConsistencyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsistencyParams.Unmarshal(m, b)
}
func (m *ConsistencyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsistencyParams.Marshal(b, m, deterministic)
}
func (m *ConsistencyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsistencyParams.Merge(m, src)
}
func (m *ConsistencyParams) XXX_Size() int {
	return xxx_messageInfo_ConsistencyParams.Size(m)
}
func (m *ConsistencyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsistencyParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConsistencyParams proto.InternalMessageInfo

func (m *ConsistencyParams) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *ConsistencyParams) GetVectors() map[string]*ConsistencyVectors {
	if m != nil {
		return m.Vectors
	}
	return nil
}

func (m *ConsistencyParams) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

// QueryCtl defines the JSON parameters that control query execution
// and which are independent of any specific pindex type.
type QueryCtl struct {
	Timeout              int64              `protobuf:"varint,1,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Consistency          *ConsistencyParams `protobuf:"bytes,2,opt,name=Consistency,proto3" json:"Consistency,omitempty"`
	PartitionSelection   string             `protobuf:"bytes,3,opt,name=PartitionSelection,proto3" json:"PartitionSelection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryCtl) Reset()         { *m = QueryCtl{} }
func (m *QueryCtl) String() string { return proto.CompactTextString(m) }
func (*QueryCtl) ProtoMessage()    {}
func (*QueryCtl) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *QueryCtl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCtl.Unmarshal(m, b)
}
func (m *QueryCtl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCtl.Marshal(b, m, deterministic)
}
func (m *QueryCtl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCtl.Merge(m, src)
}
func (m *QueryCtl) XXX_Size() int {
	return xxx_messageInfo_QueryCtl.Size(m)
}
func (m *QueryCtl) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCtl.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCtl proto.InternalMessageInfo

func (m *QueryCtl) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *QueryCtl) GetConsistency() *ConsistencyParams {
	if m != nil {
		return m.Consistency
	}
	return nil
}

func (m *QueryCtl) GetPartitionSelection() string {
	if m != nil {
		return m.PartitionSelection
	}
	return ""
}

// QueryCtlParams defines the JSON that includes the "ctl" part of a
// query request.  These "ctl" query request parameters are
// independent of any specific pindex type.
type QueryCtlParams struct {
	Ctl                  *QueryCtl `protobuf:"bytes,1,opt,name=Ctl,proto3" json:"Ctl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryCtlParams) Reset()         { *m = QueryCtlParams{} }
func (m *QueryCtlParams) String() string { return proto.CompactTextString(m) }
func (*QueryCtlParams) ProtoMessage()    {}
func (*QueryCtlParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *QueryCtlParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCtlParams.Unmarshal(m, b)
}
func (m *QueryCtlParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCtlParams.Marshal(b, m, deterministic)
}
func (m *QueryCtlParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCtlParams.Merge(m, src)
}
func (m *QueryCtlParams) XXX_Size() int {
	return xxx_messageInfo_QueryCtlParams.Size(m)
}
func (m *QueryCtlParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCtlParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCtlParams proto.InternalMessageInfo

func (m *QueryCtlParams) GetCtl() *QueryCtl {
	if m != nil {
		return m.Ctl
	}
	return nil
}

type QueryPIndexes struct {
	// An empty or nil PIndexNames means the query should use all
	// the pindexes of the index.
	PIndexNames          []string `protobuf:"bytes,1,rep,name=PIndexNames,proto3" json:"PIndexNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPIndexes) Reset()         { *m = QueryPIndexes{} }
func (m *QueryPIndexes) String() string { return proto.CompactTextString(m) }
func (*QueryPIndexes) ProtoMessage()    {}
func (*QueryPIndexes) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{6}
}

func (m *QueryPIndexes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPIndexes.Unmarshal(m, b)
}
func (m *QueryPIndexes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPIndexes.Marshal(b, m, deterministic)
}
func (m *QueryPIndexes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPIndexes.Merge(m, src)
}
func (m *QueryPIndexes) XXX_Size() int {
	return xxx_messageInfo_QueryPIndexes.Size(m)
}
func (m *QueryPIndexes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPIndexes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPIndexes proto.InternalMessageInfo

func (m *QueryPIndexes) GetPIndexNames() []string {
	if m != nil {
		return m.PIndexNames
	}
	return nil
}

type HighlightRequest struct {
	Style                string   `protobuf:"bytes,1,opt,name=Style,proto3" json:"Style,omitempty"`
	Fields               []string `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighlightRequest) Reset()         { *m = HighlightRequest{} }
func (m *HighlightRequest) String() string { return proto.CompactTextString(m) }
func (*HighlightRequest) ProtoMessage()    {}
func (*HighlightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{7}
}

func (m *HighlightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighlightRequest.Unmarshal(m, b)
}
func (m *HighlightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighlightRequest.Marshal(b, m, deterministic)
}
func (m *HighlightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighlightRequest.Merge(m, src)
}
func (m *HighlightRequest) XXX_Size() int {
	return xxx_messageInfo_HighlightRequest.Size(m)
}
func (m *HighlightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HighlightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HighlightRequest proto.InternalMessageInfo

func (m *HighlightRequest) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *HighlightRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type NumericRange struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Min                  float64  `protobuf:"fixed64,2,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  float64  `protobuf:"fixed64,3,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumericRange) Reset()         { *m = NumericRange{} }
func (m *NumericRange) String() string { return proto.CompactTextString(m) }
func (*NumericRange) ProtoMessage()    {}
func (*NumericRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{8}
}

func (m *NumericRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumericRange.Unmarshal(m, b)
}
func (m *NumericRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumericRange.Marshal(b, m, deterministic)
}
func (m *NumericRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumericRange.Merge(m, src)
}
func (m *NumericRange) XXX_Size() int {
	return xxx_messageInfo_NumericRange.Size(m)
}
func (m *NumericRange) XXX_DiscardUnknown() {
	xxx_messageInfo_NumericRange.DiscardUnknown(m)
}

var xxx_messageInfo_NumericRange proto.InternalMessageInfo

func (m *NumericRange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NumericRange) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *NumericRange) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type DateTimeRange struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTimeRange) Reset()         { *m = DateTimeRange{} }
func (m *DateTimeRange) String() string { return proto.CompactTextString(m) }
func (*DateTimeRange) ProtoMessage()    {}
func (*DateTimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{9}
}

func (m *DateTimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTimeRange.Unmarshal(m, b)
}
func (m *DateTimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTimeRange.Marshal(b, m, deterministic)
}
func (m *DateTimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTimeRange.Merge(m, src)
}
func (m *DateTimeRange) XXX_Size() int {
	return xxx_messageInfo_DateTimeRange.Size(m)
}
func (m *DateTimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_DateTimeRange proto.InternalMessageInfo

func (m *DateTimeRange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DateTimeRange) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *DateTimeRange) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type FacetRequest struct {
	Size                 int64            `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Field                string           `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	NumericRanges        []*NumericRange  `protobuf:"bytes,3,rep,name=NumericRanges,proto3" json:"NumericRanges,omitempty"`
	DateTimeRanges       []*DateTimeRange `protobuf:"bytes,4,rep,name=DateTimeRanges,proto3" json:"DateTimeRanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FacetRequest) Reset()         { *m = FacetRequest{} }
func (m *FacetRequest) String() string { return proto.CompactTextString(m) }
func (*FacetRequest) ProtoMessage()    {}
func (*FacetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{10}
}

func (m *FacetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacetRequest.Unmarshal(m, b)
}
func (m *FacetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacetRequest.Marshal(b, m, deterministic)
}
func (m *FacetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacetRequest.Merge(m, src)
}
func (m *FacetRequest) XXX_Size() int {
	return xxx_messageInfo_FacetRequest.Size(m)
}
func (m *FacetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FacetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FacetRequest proto.InternalMessageInfo

func (m *FacetRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FacetRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FacetRequest) GetNumericRanges() []*NumericRange {
	if m != nil {
		return m.NumericRanges
	}
	return nil
}

func (m *FacetRequest) GetDateTimeRanges() []*DateTimeRange {
	if m != nil {
		return m.DateTimeRanges
	}
	return nil
}

type FacetsRequest struct {
	FacetsRequests       map[string]*FacetRequest `protobuf:"bytes,1,rep,name=FacetsRequests,proto3" json:"FacetsRequests,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FacetsRequest) Reset()         { *m = FacetsRequest{} }
func (m *FacetsRequest) String() string { return proto.CompactTextString(m) }
func (*FacetsRequest) ProtoMessage()    {}
func (*FacetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{11}
}

func (m *FacetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacetsRequest.Unmarshal(m, b)
}
func (m *FacetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacetsRequest.Marshal(b, m, deterministic)
}
func (m *FacetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacetsRequest.Merge(m, src)
}
func (m *FacetsRequest) XXX_Size() int {
	return xxx_messageInfo_FacetsRequest.Size(m)
}
func (m *FacetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FacetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FacetsRequest proto.InternalMessageInfo

func (m *FacetsRequest) GetFacetsRequests() map[string]*FacetRequest {
	if m != nil {
		return m.FacetsRequests
	}
	return nil
}

type HighLightRequest struct {
	Style                string   `protobuf:"bytes,1,opt,name=Style,proto3" json:"Style,omitempty"`
	Fields               []string `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighLightRequest) Reset()         { *m = HighLightRequest{} }
func (m *HighLightRequest) String() string { return proto.CompactTextString(m) }
func (*HighLightRequest) ProtoMessage()    {}
func (*HighLightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{12}
}

func (m *HighLightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighLightRequest.Unmarshal(m, b)
}
func (m *HighLightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighLightRequest.Marshal(b, m, deterministic)
}
func (m *HighLightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighLightRequest.Merge(m, src)
}
func (m *HighLightRequest) XXX_Size() int {
	return xxx_messageInfo_HighLightRequest.Size(m)
}
func (m *HighLightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HighLightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HighLightRequest proto.InternalMessageInfo

func (m *HighLightRequest) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *HighLightRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SearchRequest struct {
	Query            []byte          `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	Size             int64           `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	From             int64           `protobuf:"varint,3,opt,name=From,proto3" json:"From,omitempty"`
	StreamOffset     int64           `protobuf:"varint,4,opt,name=StreamOffset,proto3" json:"StreamOffset,omitempty"`
	StreamSize       int64           `protobuf:"varint,5,opt,name=StreamSize,proto3" json:"StreamSize,omitempty"`
	IndexName        string          `protobuf:"bytes,6,opt,name=IndexName,proto3" json:"IndexName,omitempty"`
	IndexUUID        string          `protobuf:"bytes,7,opt,name=IndexUUID,proto3" json:"IndexUUID,omitempty"`
	Stream           bool            `protobuf:"varint,8,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Fields           []string        `protobuf:"bytes,9,rep,name=Fields,proto3" json:"Fields,omitempty"`
	QueryCtlParams   *QueryCtlParams `protobuf:"bytes,10,opt,name=queryCtlParams,proto3" json:"queryCtlParams,omitempty"`
	QueryPIndexes    *QueryPIndexes  `protobuf:"bytes,11,opt,name=queryPIndexes,proto3" json:"queryPIndexes,omitempty"`
	Score            string          `protobuf:"bytes,12,opt,name=Score,proto3" json:"Score,omitempty"`
	Sort             []byte          `protobuf:"bytes,13,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Version          string          `protobuf:"bytes,14,opt,name=Version,proto3" json:"Version,omitempty"`
	Facets           *FacetsRequest  `protobuf:"bytes,15,opt,name=Facets,proto3" json:"Facets,omitempty"`
	IncludeLocations bool            `protobuf:"varint,16,opt,name=IncludeLocations,proto3" json:"IncludeLocations,omitempty"`
	// below fields may not be needed
	Explain              bool              `protobuf:"varint,17,opt,name=Explain,proto3" json:"Explain,omitempty"`
	Highlight            *HighLightRequest `protobuf:"bytes,18,opt,name=Highlight,proto3" json:"Highlight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{13}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchRequest) GetStreamOffset() int64 {
	if m != nil {
		return m.StreamOffset
	}
	return 0
}

func (m *SearchRequest) GetStreamSize() int64 {
	if m != nil {
		return m.StreamSize
	}
	return 0
}

func (m *SearchRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *SearchRequest) GetIndexUUID() string {
	if m != nil {
		return m.IndexUUID
	}
	return ""
}

func (m *SearchRequest) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

func (m *SearchRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchRequest) GetQueryCtlParams() *QueryCtlParams {
	if m != nil {
		return m.QueryCtlParams
	}
	return nil
}

func (m *SearchRequest) GetQueryPIndexes() *QueryPIndexes {
	if m != nil {
		return m.QueryPIndexes
	}
	return nil
}

func (m *SearchRequest) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *SearchRequest) GetSort() []byte {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *SearchRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SearchRequest) GetFacets() *FacetsRequest {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *SearchRequest) GetIncludeLocations() bool {
	if m != nil {
		return m.IncludeLocations
	}
	return false
}

func (m *SearchRequest) GetExplain() bool {
	if m != nil {
		return m.Explain
	}
	return false
}

func (m *SearchRequest) GetHighlight() *HighLightRequest {
	if m != nil {
		return m.Highlight
	}
	return nil
}

type NumericRangeFacet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Min                  float64  `protobuf:"fixed64,2,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  float64  `protobuf:"fixed64,3,opt,name=Max,proto3" json:"Max,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumericRangeFacet) Reset()         { *m = NumericRangeFacet{} }
func (m *NumericRangeFacet) String() string { return proto.CompactTextString(m) }
func (*NumericRangeFacet) ProtoMessage()    {}
func (*NumericRangeFacet) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{14}
}

func (m *NumericRangeFacet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumericRangeFacet.Unmarshal(m, b)
}
func (m *NumericRangeFacet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumericRangeFacet.Marshal(b, m, deterministic)
}
func (m *NumericRangeFacet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumericRangeFacet.Merge(m, src)
}
func (m *NumericRangeFacet) XXX_Size() int {
	return xxx_messageInfo_NumericRangeFacet.Size(m)
}
func (m *NumericRangeFacet) XXX_DiscardUnknown() {
	xxx_messageInfo_NumericRangeFacet.DiscardUnknown(m)
}

var xxx_messageInfo_NumericRangeFacet proto.InternalMessageInfo

func (m *NumericRangeFacet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NumericRangeFacet) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *NumericRangeFacet) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *NumericRangeFacet) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DateRangeFacet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateRangeFacet) Reset()         { *m = DateRangeFacet{} }
func (m *DateRangeFacet) String() string { return proto.CompactTextString(m) }
func (*DateRangeFacet) ProtoMessage()    {}
func (*DateRangeFacet) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{15}
}

func (m *DateRangeFacet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateRangeFacet.Unmarshal(m, b)
}
func (m *DateRangeFacet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateRangeFacet.Marshal(b, m, deterministic)
}
func (m *DateRangeFacet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateRangeFacet.Merge(m, src)
}
func (m *DateRangeFacet) XXX_Size() int {
	return xxx_messageInfo_DateRangeFacet.Size(m)
}
func (m *DateRangeFacet) XXX_DiscardUnknown() {
	xxx_messageInfo_DateRangeFacet.DiscardUnknown(m)
}

var xxx_messageInfo_DateRangeFacet proto.InternalMessageInfo

func (m *DateRangeFacet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DateRangeFacet) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *DateRangeFacet) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *DateRangeFacet) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TermFacet struct {
	Term                 string   `protobuf:"bytes,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TermFacet) Reset()         { *m = TermFacet{} }
func (m *TermFacet) String() string { return proto.CompactTextString(m) }
func (*TermFacet) ProtoMessage()    {}
func (*TermFacet) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{16}
}

func (m *TermFacet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermFacet.Unmarshal(m, b)
}
func (m *TermFacet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermFacet.Marshal(b, m, deterministic)
}
func (m *TermFacet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermFacet.Merge(m, src)
}
func (m *TermFacet) XXX_Size() int {
	return xxx_messageInfo_TermFacet.Size(m)
}
func (m *TermFacet) XXX_DiscardUnknown() {
	xxx_messageInfo_TermFacet.DiscardUnknown(m)
}

var xxx_messageInfo_TermFacet proto.InternalMessageInfo

func (m *TermFacet) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *TermFacet) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FacetResult struct {
	Field                string               `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Total                int64                `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Missing              int64                `protobuf:"varint,3,opt,name=Missing,proto3" json:"Missing,omitempty"`
	Other                int64                `protobuf:"varint,4,opt,name=Other,proto3" json:"Other,omitempty"`
	Terms                []*TermFacet         `protobuf:"bytes,5,rep,name=Terms,proto3" json:"Terms,omitempty"`
	NumericRanges        []*NumericRangeFacet `protobuf:"bytes,6,rep,name=NumericRanges,proto3" json:"NumericRanges,omitempty"`
	DateRanges           []*DateRangeFacet    `protobuf:"bytes,7,rep,name=DateRanges,proto3" json:"DateRanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FacetResult) Reset()         { *m = FacetResult{} }
func (m *FacetResult) String() string { return proto.CompactTextString(m) }
func (*FacetResult) ProtoMessage()    {}
func (*FacetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{17}
}

func (m *FacetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacetResult.Unmarshal(m, b)
}
func (m *FacetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacetResult.Marshal(b, m, deterministic)
}
func (m *FacetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacetResult.Merge(m, src)
}
func (m *FacetResult) XXX_Size() int {
	return xxx_messageInfo_FacetResult.Size(m)
}
func (m *FacetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FacetResult.DiscardUnknown(m)
}

var xxx_messageInfo_FacetResult proto.InternalMessageInfo

func (m *FacetResult) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FacetResult) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FacetResult) GetMissing() int64 {
	if m != nil {
		return m.Missing
	}
	return 0
}

func (m *FacetResult) GetOther() int64 {
	if m != nil {
		return m.Other
	}
	return 0
}

func (m *FacetResult) GetTerms() []*TermFacet {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *FacetResult) GetNumericRanges() []*NumericRangeFacet {
	if m != nil {
		return m.NumericRanges
	}
	return nil
}

func (m *FacetResult) GetDateRanges() []*DateRangeFacet {
	if m != nil {
		return m.DateRanges
	}
	return nil
}

type ErrorMap struct {
	Error                map[string]string `protobuf:"bytes,1,rep,name=Error,proto3" json:"Error,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorMap) Reset()         { *m = ErrorMap{} }
func (m *ErrorMap) String() string { return proto.CompactTextString(m) }
func (*ErrorMap) ProtoMessage()    {}
func (*ErrorMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{18}
}

func (m *ErrorMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMap.Unmarshal(m, b)
}
func (m *ErrorMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMap.Marshal(b, m, deterministic)
}
func (m *ErrorMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMap.Merge(m, src)
}
func (m *ErrorMap) XXX_Size() int {
	return xxx_messageInfo_ErrorMap.Size(m)
}
func (m *ErrorMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMap.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMap proto.InternalMessageInfo

func (m *ErrorMap) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

type SearchStatus struct {
	Total                int64     `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Failed               int64     `protobuf:"varint,2,opt,name=Failed,proto3" json:"Failed,omitempty"`
	Successful           int64     `protobuf:"varint,3,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Errors               *ErrorMap `protobuf:"bytes,4,opt,name=Errors,proto3" json:"Errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchStatus) Reset()         { *m = SearchStatus{} }
func (m *SearchStatus) String() string { return proto.CompactTextString(m) }
func (*SearchStatus) ProtoMessage()    {}
func (*SearchStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{19}
}

func (m *SearchStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchStatus.Unmarshal(m, b)
}
func (m *SearchStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchStatus.Marshal(b, m, deterministic)
}
func (m *SearchStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchStatus.Merge(m, src)
}
func (m *SearchStatus) XXX_Size() int {
	return xxx_messageInfo_SearchStatus.Size(m)
}
func (m *SearchStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SearchStatus proto.InternalMessageInfo

func (m *SearchStatus) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchStatus) GetFailed() int64 {
	if m != nil {
		return m.Failed
	}
	return 0
}

func (m *SearchStatus) GetSuccessful() int64 {
	if m != nil {
		return m.Successful
	}
	return 0
}

func (m *SearchStatus) GetErrors() *ErrorMap {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Explanation struct {
	Value                float64        `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Message              []byte         `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Children             []*Explanation `protobuf:"bytes,3,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Explanation) Reset()         { *m = Explanation{} }
func (m *Explanation) String() string { return proto.CompactTextString(m) }
func (*Explanation) ProtoMessage()    {}
func (*Explanation) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{20}
}

func (m *Explanation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Explanation.Unmarshal(m, b)
}
func (m *Explanation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Explanation.Marshal(b, m, deterministic)
}
func (m *Explanation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Explanation.Merge(m, src)
}
func (m *Explanation) XXX_Size() int {
	return xxx_messageInfo_Explanation.Size(m)
}
func (m *Explanation) XXX_DiscardUnknown() {
	xxx_messageInfo_Explanation.DiscardUnknown(m)
}

var xxx_messageInfo_Explanation proto.InternalMessageInfo

func (m *Explanation) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Explanation) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Explanation) GetChildren() []*Explanation {
	if m != nil {
		return m.Children
	}
	return nil
}

// A SearchResult describes the results of executing
// a SearchRequest.
type SearchResult struct {
	Status               *SearchStatus      `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Request              *SearchRequest     `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
	Hits                 []byte             `protobuf:"bytes,3,opt,name=Hits,proto3" json:"Hits,omitempty"`
	Total                uint64             `protobuf:"varint,4,opt,name=Total,proto3" json:"Total,omitempty"`
	MaxScore             float64            `protobuf:"fixed64,5,opt,name=MaxScore,proto3" json:"MaxScore,omitempty"`
	Took                 *duration.Duration `protobuf:"bytes,6,opt,name=Took,proto3" json:"Took,omitempty"`
	Version              string             `protobuf:"bytes,7,opt,name=Version,proto3" json:"Version,omitempty"`
	Facets               []byte             `protobuf:"bytes,8,opt,name=Facets,proto3" json:"Facets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{21}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetStatus() *SearchStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchResult) GetRequest() *SearchRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SearchResult) GetHits() []byte {
	if m != nil {
		return m.Hits
	}
	return nil
}

func (m *SearchResult) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResult) GetMaxScore() float64 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *SearchResult) GetTook() *duration.Duration {
	if m != nil {
		return m.Took
	}
	return nil
}

func (m *SearchResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SearchResult) GetFacets() []byte {
	if m != nil {
		return m.Facets
	}
	return nil
}

type DocCountRequest struct {
	IndexName            string   `protobuf:"bytes,1,opt,name=IndexName,proto3" json:"IndexName,omitempty"`
	IndexUUID            string   `protobuf:"bytes,2,opt,name=IndexUUID,proto3" json:"IndexUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocCountRequest) Reset()         { *m = DocCountRequest{} }
func (m *DocCountRequest) String() string { return proto.CompactTextString(m) }
func (*DocCountRequest) ProtoMessage()    {}
func (*DocCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{22}
}

func (m *DocCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocCountRequest.Unmarshal(m, b)
}
func (m *DocCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocCountRequest.Marshal(b, m, deterministic)
}
func (m *DocCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocCountRequest.Merge(m, src)
}
func (m *DocCountRequest) XXX_Size() int {
	return xxx_messageInfo_DocCountRequest.Size(m)
}
func (m *DocCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocCountRequest proto.InternalMessageInfo

func (m *DocCountRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *DocCountRequest) GetIndexUUID() string {
	if m != nil {
		return m.IndexUUID
	}
	return ""
}

type DocCountResult struct {
	DocCount             int64    `protobuf:"varint,1,opt,name=DocCount,proto3" json:"DocCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocCountResult) Reset()         { *m = DocCountResult{} }
func (m *DocCountResult) String() string { return proto.CompactTextString(m) }
func (*DocCountResult) ProtoMessage()    {}
func (*DocCountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{23}
}

func (m *DocCountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocCountResult.Unmarshal(m, b)
}
func (m *DocCountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocCountResult.Marshal(b, m, deterministic)
}
func (m *DocCountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocCountResult.Merge(m, src)
}
func (m *DocCountResult) XXX_Size() int {
	return xxx_messageInfo_DocCountResult.Size(m)
}
func (m *DocCountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DocCountResult.DiscardUnknown(m)
}

var xxx_messageInfo_DocCountResult proto.InternalMessageInfo

func (m *DocCountResult) GetDocCount() int64 {
	if m != nil {
		return m.DocCount
	}
	return 0
}

// A stream SearchResult describes the streaming results
// of executing a SearchRequest.
type StreamSearchResults struct {
	// Types that are valid to be assigned to PayLoad:
	//	*StreamSearchResults_Hits
	//	*StreamSearchResults_Results
	PayLoad              isStreamSearchResults_PayLoad `protobuf_oneof:"PayLoad"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *StreamSearchResults) Reset()         { *m = StreamSearchResults{} }
func (m *StreamSearchResults) String() string { return proto.CompactTextString(m) }
func (*StreamSearchResults) ProtoMessage()    {}
func (*StreamSearchResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{24}
}

func (m *StreamSearchResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSearchResults.Unmarshal(m, b)
}
func (m *StreamSearchResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSearchResults.Marshal(b, m, deterministic)
}
func (m *StreamSearchResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSearchResults.Merge(m, src)
}
func (m *StreamSearchResults) XXX_Size() int {
	return xxx_messageInfo_StreamSearchResults.Size(m)
}
func (m *StreamSearchResults) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSearchResults.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSearchResults proto.InternalMessageInfo

type isStreamSearchResults_PayLoad interface {
	isStreamSearchResults_PayLoad()
}

type StreamSearchResults_Hits struct {
	Hits *StreamSearchResults_Batch `protobuf:"bytes,1,opt,name=Hits,proto3,oneof"`
}

type StreamSearchResults_Results struct {
	Results *StreamSearchResults_SearchResult `protobuf:"bytes,2,opt,name=Results,proto3,oneof"`
}

func (*StreamSearchResults_Hits) isStreamSearchResults_PayLoad() {}

func (*StreamSearchResults_Results) isStreamSearchResults_PayLoad() {}

func (m *StreamSearchResults) GetPayLoad() isStreamSearchResults_PayLoad {
	if m != nil {
		return m.PayLoad
	}
	return nil
}

func (m *StreamSearchResults) GetHits() *StreamSearchResults_Batch {
	if x, ok := m.GetPayLoad().(*StreamSearchResults_Hits); ok {
		return x.Hits
	}
	return nil
}

func (m *StreamSearchResults) GetResults() *StreamSearchResults_SearchResult {
	if x, ok := m.GetPayLoad().(*StreamSearchResults_Results); ok {
		return x.Results
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamSearchResults) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamSearchResults_OneofMarshaler, _StreamSearchResults_OneofUnmarshaler, _StreamSearchResults_OneofSizer, []interface{}{
		(*StreamSearchResults_Hits)(nil),
		(*StreamSearchResults_Results)(nil),
	}
}

func _StreamSearchResults_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamSearchResults)
	// PayLoad
	switch x := m.PayLoad.(type) {
	case *StreamSearchResults_Hits:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hits); err != nil {
			return err
		}
	case *StreamSearchResults_Results:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Results); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamSearchResults.PayLoad has unexpected type %T", x)
	}
	return nil
}

func _StreamSearchResults_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamSearchResults)
	switch tag {
	case 1: // PayLoad.Hits
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamSearchResults_Batch)
		err := b.DecodeMessage(msg)
		m.PayLoad = &StreamSearchResults_Hits{msg}
		return true, err
	case 2: // PayLoad.Results
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamSearchResults_SearchResult)
		err := b.DecodeMessage(msg)
		m.PayLoad = &StreamSearchResults_Results{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamSearchResults_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamSearchResults)
	// PayLoad
	switch x := m.PayLoad.(type) {
	case *StreamSearchResults_Hits:
		s := proto.Size(x.Hits)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamSearchResults_Results:
		s := proto.Size(x.Results)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// a separate wrapper type is needed for hits as protobuf
// doesn't allow `repeated` keyword inside a oneof message
type StreamSearchResults_SearchResult struct {
	Request              *SearchRequest     `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Status               *SearchStatus      `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Total                uint64             `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	MaxScore             float64            `protobuf:"fixed64,4,opt,name=MaxScore,proto3" json:"MaxScore,omitempty"`
	Took                 *duration.Duration `protobuf:"bytes,5,opt,name=Took,proto3" json:"Took,omitempty"`
	Hits                 []byte             `protobuf:"bytes,6,opt,name=Hits,proto3" json:"Hits,omitempty"`
	Facets               []byte             `protobuf:"bytes,7,opt,name=Facets,proto3" json:"Facets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamSearchResults_SearchResult) Reset()         { *m = StreamSearchResults_SearchResult{} }
func (m *StreamSearchResults_SearchResult) String() string { return proto.CompactTextString(m) }
func (*StreamSearchResults_SearchResult) ProtoMessage()    {}
func (*StreamSearchResults_SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{24, 0}
}

func (m *StreamSearchResults_SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSearchResults_SearchResult.Unmarshal(m, b)
}
func (m *StreamSearchResults_SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSearchResults_SearchResult.Marshal(b, m, deterministic)
}
func (m *StreamSearchResults_SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSearchResults_SearchResult.Merge(m, src)
}
func (m *StreamSearchResults_SearchResult) XXX_Size() int {
	return xxx_messageInfo_StreamSearchResults_SearchResult.Size(m)
}
func (m *StreamSearchResults_SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSearchResults_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSearchResults_SearchResult proto.InternalMessageInfo

func (m *StreamSearchResults_SearchResult) GetRequest() *SearchRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *StreamSearchResults_SearchResult) GetStatus() *SearchStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StreamSearchResults_SearchResult) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StreamSearchResults_SearchResult) GetMaxScore() float64 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *StreamSearchResults_SearchResult) GetTook() *duration.Duration {
	if m != nil {
		return m.Took
	}
	return nil
}

func (m *StreamSearchResults_SearchResult) GetHits() []byte {
	if m != nil {
		return m.Hits
	}
	return nil
}

func (m *StreamSearchResults_SearchResult) GetFacets() []byte {
	if m != nil {
		return m.Facets
	}
	return nil
}

type StreamSearchResults_Batch struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Offsets              []uint64 `protobuf:"varint,2,rep,packed,name=Offsets,proto3" json:"Offsets,omitempty"`
	Total                uint64   `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamSearchResults_Batch) Reset()         { *m = StreamSearchResults_Batch{} }
func (m *StreamSearchResults_Batch) String() string { return proto.CompactTextString(m) }
func (*StreamSearchResults_Batch) ProtoMessage()    {}
func (*StreamSearchResults_Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{24, 1}
}

func (m *StreamSearchResults_Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSearchResults_Batch.Unmarshal(m, b)
}
func (m *StreamSearchResults_Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSearchResults_Batch.Marshal(b, m, deterministic)
}
func (m *StreamSearchResults_Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSearchResults_Batch.Merge(m, src)
}
func (m *StreamSearchResults_Batch) XXX_Size() int {
	return xxx_messageInfo_StreamSearchResults_Batch.Size(m)
}
func (m *StreamSearchResults_Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSearchResults_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSearchResults_Batch proto.InternalMessageInfo

func (m *StreamSearchResults_Batch) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *StreamSearchResults_Batch) GetOffsets() []uint64 {
	if m != nil {
		return m.Offsets
	}
	return nil
}

func (m *StreamSearchResults_Batch) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("search.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*HealthCheckRequest)(nil), "search.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "search.HealthCheckResponse")
	proto.RegisterType((*ConsistencyVectors)(nil), "search.ConsistencyVectors")
	proto.RegisterMapType((map[string]uint64)(nil), "search.ConsistencyVectors.ConsistencyVectorEntry")
	proto.RegisterType((*ConsistencyParams)(nil), "search.ConsistencyParams")
	proto.RegisterMapType((map[string]*ConsistencyVectors)(nil), "search.ConsistencyParams.VectorsEntry")
	proto.RegisterType((*QueryCtl)(nil), "search.QueryCtl")
	proto.RegisterType((*QueryCtlParams)(nil), "search.QueryCtlParams")
	proto.RegisterType((*QueryPIndexes)(nil), "search.QueryPIndexes")
	proto.RegisterType((*HighlightRequest)(nil), "search.HighlightRequest")
	proto.RegisterType((*NumericRange)(nil), "search.numericRange")
	proto.RegisterType((*DateTimeRange)(nil), "search.dateTimeRange")
	proto.RegisterType((*FacetRequest)(nil), "search.FacetRequest")
	proto.RegisterType((*FacetsRequest)(nil), "search.FacetsRequest")
	proto.RegisterMapType((map[string]*FacetRequest)(nil), "search.FacetsRequest.FacetsRequestsEntry")
	proto.RegisterType((*HighLightRequest)(nil), "search.HighLightRequest")
	proto.RegisterType((*SearchRequest)(nil), "search.SearchRequest")
	proto.RegisterType((*NumericRangeFacet)(nil), "search.NumericRangeFacet")
	proto.RegisterType((*DateRangeFacet)(nil), "search.DateRangeFacet")
	proto.RegisterType((*TermFacet)(nil), "search.TermFacet")
	proto.RegisterType((*FacetResult)(nil), "search.FacetResult")
	proto.RegisterType((*ErrorMap)(nil), "search.ErrorMap")
	proto.RegisterMapType((map[string]string)(nil), "search.ErrorMap.ErrorEntry")
	proto.RegisterType((*SearchStatus)(nil), "search.SearchStatus")
	proto.RegisterType((*Explanation)(nil), "search.Explanation")
	proto.RegisterType((*SearchResult)(nil), "search.SearchResult")
	proto.RegisterType((*DocCountRequest)(nil), "search.DocCountRequest")
	proto.RegisterType((*DocCountResult)(nil), "search.DocCountResult")
	proto.RegisterType((*StreamSearchResults)(nil), "search.StreamSearchResults")
	proto.RegisterType((*StreamSearchResults_SearchResult)(nil), "search.StreamSearchResults.SearchResult")
	proto.RegisterType((*StreamSearchResults_Batch)(nil), "search.StreamSearchResults.Batch")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 1501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x72, 0x13, 0x37,
	0x14, 0x66, 0xfd, 0xef, 0x63, 0xc7, 0x38, 0x4a, 0x48, 0xb7, 0xa6, 0xc3, 0xa4, 0x7b, 0xd1, 0xa6,
	0x0c, 0x38, 0x90, 0xb6, 0x94, 0x81, 0x29, 0xa5, 0xe4, 0xa7, 0xc9, 0x90, 0x38, 0x41, 0x0e, 0xe1,
	0x92, 0x59, 0xd6, 0x8a, 0xbd, 0xc3, 0x7a, 0x37, 0xac, 0xd6, 0x34, 0xee, 0x03, 0xf4, 0xa6, 0x57,
	0x9d, 0xe1, 0x4d, 0x7a, 0xd9, 0x77, 0xe8, 0x1b, 0xf4, 0x09, 0x78, 0x83, 0x5e, 0x75, 0x74, 0x24,
	0xad, 0xb5, 0xb6, 0x03, 0x19, 0xee, 0xf4, 0x1d, 0x9d, 0x73, 0x74, 0xfe, 0x25, 0x41, 0x9d, 0x33,
	0x37, 0xf6, 0x06, 0xed, 0xb3, 0x38, 0x4a, 0x22, 0x52, 0x92, 0xa8, 0x75, 0xa3, 0x1f, 0x45, 0xfd,
	0x80, 0xad, 0x23, 0xf5, 0xd5, 0xe8, 0x74, 0xbd, 0x37, 0x8a, 0xdd, 0xc4, 0x8f, 0x42, 0xc9, 0xe7,
	0xb4, 0x81, 0xec, 0x32, 0x37, 0x48, 0x06, 0x9b, 0x03, 0xe6, 0xbd, 0xa6, 0xec, 0xcd, 0x88, 0xf1,
	0x84, 0xd8, 0x50, 0xe6, 0x2c, 0x7e, 0xeb, 0x7b, 0xcc, 0xb6, 0x56, 0xad, 0xb5, 0x2a, 0xd5, 0xd0,
	0x79, 0x67, 0xc1, 0x52, 0x46, 0x80, 0x9f, 0x45, 0x21, 0x67, 0xe4, 0x67, 0x28, 0xf1, 0xc4, 0x4d,
	0x46, 0x1c, 0x05, 0x1a, 0x1b, 0xdf, 0xb4, 0x95, 0x39, 0x73, 0x98, 0xdb, 0x5d, 0xa1, 0x2c, 0xec,
	0x77, 0x51, 0x80, 0x2a, 0x41, 0xe7, 0x01, 0x2c, 0x64, 0x36, 0x48, 0x0d, 0xca, 0xcf, 0x3b, 0x4f,
	0x3b, 0x87, 0x2f, 0x3a, 0xcd, 0x2b, 0x02, 0x74, 0xb7, 0xe9, 0xc9, 0x5e, 0xe7, 0x97, 0xa6, 0x45,
	0xae, 0x42, 0xad, 0x73, 0x78, 0xfc, 0x52, 0x13, 0x72, 0xce, 0xdf, 0x16, 0x90, 0xcd, 0x28, 0xe4,
	0x3e, 0x4f, 0x58, 0xe8, 0x8d, 0x4f, 0x98, 0x97, 0x44, 0x31, 0x27, 0x2f, 0x61, 0x71, 0x86, 0x6a,
	0x5b, 0xab, 0xf9, 0xb5, 0xda, 0xc6, 0x5d, 0x6d, 0xe0, 0xac, 0xd8, 0x2c, 0x69, 0x3b, 0x4c, 0xe2,
	0x31, 0x9d, 0xd5, 0xd5, 0xda, 0x82, 0x95, 0xf9, 0xcc, 0xa4, 0x09, 0xf9, 0xd7, 0x6c, 0xac, 0xc2,
	0x27, 0x96, 0x64, 0x19, 0x8a, 0x6f, 0xdd, 0x60, 0xc4, 0xec, 0xdc, 0xaa, 0xb5, 0x56, 0xa0, 0x12,
	0x3c, 0xc8, 0xdd, 0xb7, 0x9c, 0x7f, 0xad, 0x8c, 0x9d, 0x47, 0x6e, 0xec, 0x0e, 0xb9, 0xe0, 0xdf,
	0x67, 0x6f, 0x59, 0xa0, 0x74, 0x48, 0x40, 0x1e, 0x43, 0x59, 0x99, 0x69, 0xe7, 0xd0, 0x91, 0xaf,
	0xe6, 0x38, 0x22, 0x35, 0xb4, 0x15, 0xa3, 0xb4, 0x5e, 0x8b, 0x89, 0xe4, 0x52, 0xc6, 0x47, 0x41,
	0xc2, 0xed, 0xbc, 0x4c, 0xae, 0x82, 0xad, 0x13, 0xa8, 0x9b, 0x22, 0x73, 0x7c, 0xb8, 0x63, 0xfa,
	0x50, 0xdb, 0x68, 0x5d, 0x1c, 0x44, 0xd3, 0xbf, 0x3f, 0x2d, 0xa8, 0x3c, 0x1b, 0xb1, 0x78, 0xbc,
	0x99, 0x04, 0xe2, 0xf8, 0x63, 0x7f, 0xc8, 0xa2, 0x51, 0x82, 0x8a, 0xf3, 0x54, 0x43, 0xf2, 0x10,
	0x6a, 0x86, 0x1e, 0x75, 0xc4, 0xe7, 0x17, 0xba, 0x47, 0x4d, 0x6e, 0xd2, 0x06, 0x72, 0xe4, 0xc6,
	0x89, 0x2f, 0x6a, 0xbb, 0xcb, 0x02, 0xe6, 0x89, 0x85, 0x72, 0x70, 0xce, 0x8e, 0xf3, 0x1d, 0x34,
	0xb4, 0x49, 0x2a, 0xde, 0x0e, 0xe4, 0x37, 0x13, 0x19, 0xed, 0xda, 0x46, 0x53, 0x1f, 0xab, 0x99,
	0xa8, 0xd8, 0x74, 0xee, 0xc2, 0x02, 0x12, 0x8e, 0xf6, 0xc2, 0x1e, 0x3b, 0x67, 0x9c, 0xac, 0x42,
	0x4d, 0xae, 0x3b, 0xee, 0x90, 0x71, 0xac, 0xad, 0x2a, 0x35, 0x49, 0xce, 0x63, 0x68, 0xee, 0xfa,
	0xfd, 0x41, 0xe0, 0xf7, 0x07, 0x89, 0xee, 0xaf, 0x65, 0x28, 0x76, 0x93, 0x71, 0xa0, 0xbb, 0x4b,
	0x02, 0xb2, 0x02, 0xa5, 0x1d, 0x9f, 0x05, 0x3d, 0x99, 0xd9, 0x2a, 0x55, 0xc8, 0xd9, 0x81, 0x7a,
	0x38, 0x1a, 0xb2, 0xd8, 0xf7, 0xa8, 0x1b, 0xf6, 0x19, 0x21, 0x50, 0x10, 0xaa, 0x95, 0x30, 0xae,
	0x45, 0xaa, 0x0e, 0xfc, 0x10, 0x63, 0x66, 0x51, 0xb1, 0x44, 0x8a, 0x7b, 0x8e, 0x11, 0x10, 0x14,
	0xf7, 0xdc, 0x79, 0x0a, 0x0b, 0x3d, 0x37, 0x61, 0x22, 0xdc, 0x17, 0x2b, 0x42, 0xd3, 0xdc, 0x38,
	0x41, 0x55, 0x68, 0x9a, 0x1b, 0x27, 0x42, 0xd9, 0x76, 0xd8, 0x53, 0xe1, 0x14, 0x4b, 0xe7, 0x2f,
	0x0b, 0xea, 0x3b, 0xae, 0xc7, 0x52, 0x9f, 0x08, 0x14, 0xba, 0xfe, 0x6f, 0x4c, 0x25, 0x15, 0xd7,
	0x42, 0x19, 0xfa, 0xa0, 0x95, 0x21, 0x20, 0x0f, 0x60, 0xa1, 0x63, 0xf8, 0x23, 0xca, 0x50, 0x14,
	0xf2, 0xb2, 0x0e, 0xb9, 0xe9, 0x2c, 0xcd, 0xb2, 0x92, 0x1f, 0xa1, 0xb1, 0x65, 0xfa, 0xc0, 0xed,
	0x02, 0x0a, 0x5f, 0xd3, 0xc2, 0x19, 0x0f, 0xe9, 0x14, 0xb3, 0x98, 0x13, 0x0b, 0x68, 0x35, 0xd7,
	0x66, 0x3f, 0x83, 0x46, 0x86, 0xc0, 0xd5, 0x7c, 0x48, 0x07, 0x58, 0x66, 0x37, 0x8b, 0x54, 0x67,
	0x4d, 0x29, 0x68, 0xbd, 0x80, 0xa5, 0x39, 0x6c, 0x73, 0xba, 0xe9, 0x66, 0xb6, 0x9b, 0x96, 0x33,
	0x47, 0x2a, 0x61, 0xb3, 0x8f, 0x54, 0x29, 0xed, 0x7f, 0x7a, 0x29, 0xbd, 0x2f, 0x88, 0x21, 0x2b,
	0x0e, 0x31, 0xe4, 0xb1, 0xa2, 0x51, 0xbe, 0x4e, 0x25, 0x48, 0x93, 0x99, 0x33, 0x92, 0x49, 0xa0,
	0xb0, 0x13, 0x47, 0x43, 0x2c, 0x82, 0x3c, 0xc5, 0x35, 0x71, 0xa0, 0xde, 0x4d, 0x62, 0xe6, 0x0e,
	0x0f, 0x4f, 0x4f, 0x39, 0x4b, 0xec, 0x02, 0xee, 0x65, 0x68, 0xe4, 0x06, 0x80, 0xc4, 0xa8, 0xb1,
	0x88, 0x1c, 0x06, 0x85, 0x7c, 0x01, 0xd5, 0xb4, 0x5d, 0xec, 0x12, 0x7a, 0x31, 0x21, 0xa4, 0xbb,
	0xcf, 0x9f, 0xef, 0x6d, 0xd9, 0x65, 0x63, 0x57, 0x10, 0x84, 0x9f, 0x52, 0x93, 0x5d, 0x59, 0xb5,
	0xd6, 0x2a, 0x54, 0x21, 0xc3, 0xff, 0xaa, 0xe9, 0x3f, 0x79, 0x04, 0x8d, 0x37, 0x99, 0xae, 0xb7,
	0x01, 0x43, 0xbf, 0x32, 0xdd, 0xee, 0x6a, 0xc4, 0x4c, 0x71, 0x93, 0x87, 0xb0, 0xf0, 0xc6, 0xec,
	0x7f, 0xbb, 0x86, 0xe2, 0xd7, 0x32, 0xe2, 0x7a, 0x93, 0x66, 0x79, 0x31, 0x55, 0x5e, 0x14, 0x33,
	0xbb, 0xae, 0x52, 0x25, 0x00, 0x86, 0x3a, 0x8a, 0x13, 0x7b, 0x01, 0xe3, 0x8f, 0x6b, 0x31, 0x23,
	0x4f, 0x58, 0xcc, 0xc5, 0x04, 0x6b, 0xc8, 0x11, 0xad, 0x20, 0xb9, 0x0d, 0x25, 0x59, 0x5b, 0xf6,
	0xd5, 0xec, 0xc9, 0x99, 0x8a, 0xa3, 0x8a, 0x89, 0xdc, 0x84, 0xe6, 0x5e, 0xe8, 0x05, 0xa3, 0x1e,
	0xdb, 0x8f, 0x3c, 0xbc, 0xf7, 0xb9, 0xdd, 0xc4, 0x48, 0xcd, 0xd0, 0xc5, 0xa1, 0xdb, 0xe7, 0x67,
	0x81, 0xeb, 0x87, 0xf6, 0x22, 0xb2, 0x68, 0x48, 0xee, 0x41, 0x35, 0x1d, 0x61, 0x36, 0xc1, 0x73,
	0xed, 0xf4, 0x7e, 0x9f, 0x2a, 0x48, 0x3a, 0x61, 0x75, 0x5c, 0x58, 0x34, 0xbb, 0x17, 0x6d, 0xfa,
	0xd4, 0xe9, 0x25, 0xa2, 0xb7, 0x19, 0x8d, 0x42, 0x5d, 0x63, 0x12, 0x38, 0xaf, 0xe4, 0x3c, 0xf8,
	0x88, 0xfe, 0x4b, 0x0e, 0xb5, 0x0b, 0xce, 0xf8, 0x1e, 0xaa, 0xc7, 0x2c, 0x1e, 0xa6, 0xea, 0x05,
	0xd0, 0xea, 0xc5, 0x7a, 0x22, 0x96, 0x33, 0xc5, 0xfe, 0xc8, 0x41, 0x4d, 0x75, 0xb2, 0xb8, 0x5e,
	0x27, 0xc3, 0xd0, 0x32, 0x87, 0xe1, 0x32, 0x14, 0x8f, 0xa3, 0xc4, 0x0d, 0xb4, 0x2c, 0x02, 0x91,
	0x8b, 0x03, 0x9f, 0x73, 0x3f, 0xec, 0xab, 0x76, 0xd3, 0x50, 0xf0, 0x1f, 0x26, 0x03, 0x16, 0x6b,
	0x13, 0x11, 0x90, 0xaf, 0xa1, 0x28, 0x2c, 0xe1, 0x76, 0x11, 0x87, 0xd7, 0xa2, 0xce, 0x4e, 0x6a,
	0x37, 0x95, 0xfb, 0xe4, 0xa7, 0xe9, 0xd9, 0x5b, 0x42, 0x81, 0xf4, 0x96, 0x9d, 0xc9, 0xd7, 0xf4,
	0x00, 0xbe, 0x07, 0x90, 0x06, 0x9c, 0xdb, 0x65, 0x94, 0x4e, 0xbb, 0x27, 0x9b, 0x0a, 0x6a, 0x70,
	0x3a, 0xbf, 0x42, 0x65, 0x3b, 0x8e, 0xa3, 0xf8, 0xc0, 0x3d, 0x23, 0x77, 0xa1, 0x88, 0x6b, 0x35,
	0x6a, 0xaf, 0x6b, 0x71, 0xcd, 0x20, 0x17, 0x72, 0xb8, 0x4a, 0xce, 0xd6, 0x7d, 0x80, 0x09, 0xf1,
	0x63, 0x8f, 0xab, 0xaa, 0x39, 0x34, 0x7f, 0xb7, 0xa0, 0x2e, 0x47, 0x9e, 0x7a, 0x56, 0xa6, 0x11,
	0xb7, 0xcc, 0x88, 0x8b, 0x89, 0xe1, 0xfa, 0x01, 0xeb, 0xa9, 0x44, 0x28, 0x84, 0xd3, 0x6b, 0xe4,
	0x79, 0x8c, 0xf3, 0xd3, 0x51, 0xa0, 0x92, 0x61, 0x50, 0xc8, 0x1a, 0x94, 0xd0, 0x30, 0x8e, 0x09,
	0x31, 0x1e, 0x0e, 0xda, 0x19, 0xaa, 0xf6, 0x9d, 0x10, 0x6a, 0xd8, 0x50, 0x21, 0xf6, 0x9b, 0x30,
	0xe3, 0x04, 0x2d, 0xb6, 0xb0, 0xc6, 0x25, 0xc0, 0xc4, 0x33, 0xce, 0xdd, 0xbe, 0xf4, 0xa4, 0x4e,
	0x35, 0x24, 0xeb, 0x50, 0xd9, 0x1c, 0xf8, 0x41, 0x2f, 0x66, 0xa1, 0xba, 0x30, 0x97, 0xd2, 0xa3,
	0x26, 0x6a, 0x69, 0xca, 0xe4, 0xbc, 0xcb, 0x69, 0xc7, 0x55, 0x01, 0xde, 0x12, 0xc3, 0x32, 0x7d,
	0xa3, 0x1b, 0xf7, 0x8d, 0x19, 0x1e, 0xaa, 0x78, 0xc8, 0xba, 0x78, 0x26, 0x62, 0x4b, 0xab, 0xeb,
	0xe9, 0x5a, 0x96, 0x5d, 0xf7, 0x7b, 0xd9, 0x78, 0x00, 0xec, 0xfa, 0xea, 0x51, 0x59, 0xa7, 0xb8,
	0x9e, 0xc4, 0xba, 0x20, 0xdf, 0xbc, 0x32, 0xd6, 0x2d, 0xa8, 0x1c, 0xb8, 0xe7, 0x72, 0x16, 0x16,
	0xd1, 0xfb, 0x14, 0x93, 0xdb, 0x50, 0x38, 0x8e, 0xa2, 0xd7, 0x78, 0x11, 0x88, 0xba, 0x94, 0xff,
	0x97, 0xb6, 0xfe, 0xbf, 0xb4, 0xb7, 0xd4, 0xff, 0x85, 0x22, 0x9b, 0x39, 0x29, 0xcb, 0xd9, 0x49,
	0xb9, 0x92, 0x4e, 0xca, 0x0a, 0x1a, 0xa4, 0x90, 0x73, 0x00, 0x57, 0xb7, 0x22, 0x0f, 0x5b, 0x54,
	0x5b, 0x9e, 0xb9, 0x81, 0xac, 0x0f, 0xde, 0x40, 0xb9, 0xa9, 0x1b, 0xc8, 0xb9, 0x05, 0x8d, 0x89,
	0x3a, 0x0c, 0x73, 0x0b, 0x2a, 0x9a, 0xa2, 0x4a, 0x2c, 0xc5, 0xce, 0xfb, 0x3c, 0x2c, 0xa9, 0xab,
	0xcf, 0xc8, 0x0c, 0x27, 0x3f, 0xa8, 0xd8, 0xc9, 0xc4, 0x7c, 0x99, 0x46, 0x7a, 0x96, 0xb5, 0xfd,
	0xc4, 0x4d, 0xbc, 0xc1, 0xee, 0x15, 0x15, 0xe0, 0xad, 0xc9, 0x63, 0x5e, 0x66, 0x69, 0xed, 0x43,
	0xb2, 0x26, 0xda, 0xbd, 0x32, 0x79, 0xf8, 0xff, 0x67, 0x4d, 0x95, 0x8a, 0x91, 0x7c, 0xeb, 0x52,
	0xc9, 0x9f, 0xd4, 0x56, 0xee, 0x12, 0xb5, 0x95, 0x96, 0x45, 0xfe, 0xa2, 0xb2, 0x28, 0x5c, 0x50,
	0x16, 0xc5, 0xcb, 0x95, 0x85, 0xae, 0xc5, 0x92, 0x51, 0x8b, 0x93, 0x82, 0x28, 0x9b, 0x05, 0xd1,
	0x3a, 0x80, 0x22, 0xc6, 0x54, 0x58, 0xf5, 0x64, 0x9c, 0x30, 0xae, 0x9f, 0x42, 0x08, 0x44, 0x85,
	0xc9, 0x87, 0x8c, 0x7c, 0x4b, 0x15, 0xa8, 0x86, 0xf3, 0xbd, 0x78, 0x52, 0x85, 0xf2, 0x91, 0x3b,
	0xde, 0x8f, 0xdc, 0xde, 0xc6, 0x3f, 0x96, 0x7e, 0x6d, 0x75, 0xe5, 0xf7, 0x99, 0x3c, 0x82, 0x92,
	0x24, 0x90, 0xf9, 0x01, 0x6d, 0x5d, 0xff, 0x40, 0xfa, 0xee, 0x58, 0xe4, 0x31, 0x14, 0xf1, 0x2b,
	0x4d, 0x5a, 0x73, 0xff, 0xd7, 0x53, 0x3a, 0xe6, 0x7d, 0xd4, 0x1f, 0x4e, 0xaa, 0x93, 0x7c, 0x96,
	0xce, 0xed, 0x6c, 0x43, 0xb4, 0x56, 0x66, 0x37, 0x84, 0x05, 0xaf, 0x4a, 0x18, 0xef, 0x6f, 0xff,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x57, 0xed, 0x71, 0xac, 0x6c, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	// external rpcs, for rpc clients
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (SearchService_SearchClient, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	DocCount(ctx context.Context, in *DocCountRequest, opts ...grpc.CallOption) (*DocCountResult, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (SearchService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SearchService_serviceDesc.Streams[0], "/search.SearchService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SearchService_SearchClient interface {
	Recv() (*StreamSearchResults, error)
	grpc.ClientStream
}

type searchServiceSearchClient struct {
	grpc.ClientStream
}

func (x *searchServiceSearchClient) Recv() (*StreamSearchResults, error) {
	m := new(StreamSearchResults)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *searchServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DocCount(ctx context.Context, in *DocCountRequest, opts ...grpc.CallOption) (*DocCountResult, error) {
	out := new(DocCountResult)
	err := c.cc.Invoke(ctx, "/search.SearchService/DocCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	// external rpcs, for rpc clients
	Search(*SearchRequest, SearchService_SearchServer) error
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	DocCount(context.Context, *DocCountRequest) (*DocCountResult, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchServiceServer).Search(m, &searchServiceSearchServer{stream})
}

type SearchService_SearchServer interface {
	Send(*StreamSearchResults) error
	grpc.ServerStream
}

type searchServiceSearchServer struct {
	grpc.ServerStream
}

func (x *searchServiceSearchServer) Send(m *StreamSearchResults) error {
	return x.ServerStream.SendMsg(m)
}

func _SearchService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DocCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DocCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/DocCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DocCount(ctx, req.(*DocCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _SearchService_Check_Handler,
		},
		{
			MethodName: "DocCount",
			Handler:    _SearchService_DocCount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _SearchService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search.proto",
}
